version: "3.8"

# Default labels for MyBackup
x-mybackup-labels: &default-mybackup-labels  #bu bir anchor( etiket) olarak tan覺mlan覺r
  mybackup.name: "MyBackup" 
  mybackup.enable: "true"
  mybackup.port: "3306"
  mybackup.user: "root"
  mybackup.password: "Hamza112113172028"
  mybackup.backup_format: "both"

services:
  mysql:
    container_name: mysql
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: Hamza112113172028
      MYSQL_DATABASE: ilkveriTabani
    labels:
      <<: *default-mybackup-labels # bu sat覺r, default-mybackup-labels etiketini kullan覺r 
      mybackup.host: "mysql"
      mybackup.backup_times: "17:00,19:00,23:00"
      mybackup.backup_folder: "ilke4"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data-mysql:/var/lib/mysql
    ports:
      - "3320:3306"
    networks:
      - database-network

  hamza:
    container_name: hamza
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: Hamza112113172028
      MYSQL_DATABASE: ikinciveriTabani
    labels:
      <<: *default-mybackup-labels
      mybackup.host: "hamza"
      mybackup.backup_interval_hours: "0.5"
      mybackup.backup_folder: "ilke3"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data-hamza:/var/lib/mysql
    ports:
      - "3321:3306"
    networks:
      - database-network

  hamzam:
    container_name: hamzam
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: Hamza112113172028
      MYSQL_DATABASE: ucncuveritabani
    labels:
      <<: *default-mybackup-labels
      mybackup.host: "hamzam"
      mybackup.backup_interval_hours: "0.0833"
      mybackup.backup_folder: "ilke"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data-hamzam:/var/lib/mysql
    ports:
      - "3322:3306"
    networks:
      - database-network

  testdb:
    container_name: testdb
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: Hamza112113172028
      MYSQL_DATABASE: besinciveritabani
    labels:
      <<: *default-mybackup-labels
      mybackup.host: "testdb"
      mybackup.backup_interval_hours: "0.0833"
      mybackup.backup_folder: "ilke1"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data-testdb:/var/lib/mysql
    ports:
      - "3324:3306"
    networks:
      - database-network

  deneme:
    container_name: deneme
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: Hamza112113172028
      MYSQL_DATABASE: dorduncuveriTabani
    labels:
      <<: *default-mybackup-labels
      mybackup.host: "deneme"
      mybackup.backup_interval_hours: "1"
      mybackup.backup_folder: "ilke2"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data-deneme:/var/lib/mysql
    ports:
      - "3323:3306"
    networks:
      - database-network

  backup-service:
    build: ./backup-service
    container_name: database-backup-service
    depends_on:
      - mysql
      - hamza
      - hamzam
      - deneme
      - testdb
    volumes:
      - ./backups:/app/backups
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
